# Copyright (C) 2025 NunoLealF
# This file is part of the Serra project, which is released under the MIT license.
# For more information, please refer to the accompanying license agreement. <3

# ------------------------------ Build options ------------------------------

  # Should the Debug flag be enabled? (false/true)
    Debug := true

  # Build for legacy (BIOS) targets? (false/true)
    BuildBios := true

  # Build for EFI targets? (false/true)
    BuildEfi := true

  # Build an unpartitioned, MBR or GPT image? (unpart/mbr/gpt)                     *TODO* MBR is still unfinished, and I havent even bothered with GPT yet.
    ImageType := mbr

  # What should the size of the FAT partition be, in MiB? (%d)
    PartitionSize := 24

  # How many sectors per FAT cluster? (%d)
    ClusterSize := 8

  # *If building a partitioned image*, then:
    # How large should it be, in MiB? (%d)
      ImageSize := 32
    # What sector size should be used, in bytes? (%d)
      SectorSize := 512
    # What LBA should the partition start at? (%d)
      PartitionLba := 2048

# ------------------------------ Configuration ------------------------------

  # (Other things)

    CFLAGS += -DDebug=$(Debug)

  # (SFDisk configuration, for legacy/MBR targets)

    define SFDISK_MBR_CONFIGURATION

    	label: dos

    	unit: sectors
    	first-lba: $(PartitionLba)
    	sector-size: $(SectorSize)

    	start=$(PartitionLba), size=$(PartitionSize)M, type=0xEF, bootable

    endef

  # (SFDisk configuration, for GPT targets)

    define SFDISK_GPT_CONFIGURATION
    endef
