# Copyright (C) 2025 NunoLealF
# This file is part of the Serra project, which is released under the MIT license.
# For more information, please refer to the accompanying license agreement. <3

# ------------------------------ Build options ------------------------------

  # Should the Debug flag be enabled? (false/true)
    Debug := true

  # Should graphics mode be used? (false/true)
    Graphical := true

  # Build for legacy (BIOS) targets? (false/true)
    BuildBios := true

  # Build for EFI targets? (false/true)
    BuildEfi := true

  # Build an unpartitioned, MBR or GPT image? (unpart/mbr/gpt)
    ImageType := mbr

  # *If building an unpartitioned image*, then:
    # What sector size should be used, in bytes? (*)
      SectorSize := 512

  # *If building a partitioned image*, then:
    # How large should it be, in MiB? (*)
      ImageSize := 32
    # What LBA should the partition start at? (*)
      PartitionLba := 2048

  # How large should the FAT partition be, in MiB? (*)
    PartitionSize := 24

  # How many sectors should each FAT cluster have? (*)
    ClusterSize := 8

  # How much usable memory should the kernel require, in MiB? (*)
    KernelMb := 128

# ------------------------------ Configuration ------------------------------

  # (Other things)

    CFLAGS += -DDebug=$(Debug) -DGraphical=$(Graphical) -DKernelMb=$(KernelMb)

  # (SFDisk configuration, for legacy/MBR targets)

    define SFDISK_MBR_CONFIGURATION

    	label: dos

    	unit: sectors
    	first-lba: $(PartitionLba)
    	sector-size: 512

    	start=$(PartitionLba), size=$(PartitionSize)M, type=0xEF, bootable

    endef

  # (SFDisk configuration, for GPT targets)

    define SFDISK_GPT_CONFIGURATION

      label: gpt

      unit: sectors
      first-lba: $(PartitionLba)
      sector-size: 512

      start=$(PartitionLba), size=$(PartitionSize)M, attrs="RequiredPartition", type=U

    endef
